// app/layout.tsx
import type { Metadata } from "next";
import { Manrope } from 'next/font/google';
import Header from "./components/Header/Header";
import "./globals.css";
import { AuthProvider } from './AuthContext';

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className} style={{ height: "100vh", background: "#FCFCFE", color: "black" }}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}